baseURL = "/"
themesDir = "themes"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "Projektor Docs"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Code"
    url = "https://github.com/craigatk/projektor"
    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Projektor is a convenient way to view full test results from continuous integration (CI) servers'
  homepage_image = '/images/projektor-results-dashboard.png'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Projektor is a convenient way to view full test results from continuous integration (CI) servers"
    meta_og_title = "Projektor Docs"
    meta_og_type = "website"
    meta_og_url = "https://projektor.dev"
    meta_og_image = "images/projektor-results-dashboard.png"
    meta_og_description = "Projektor is a convenient way to view full test results from continuous integration (CI) servers"
    meta_twitter_card = "summary"
    meta_twitter_site = "@atk.craig1"
    meta_twitter_creator = "@atk.craig1"

  [params.logo]
      mobile = "/images/projektor-logo.png"
      standard  = "/images/projektor-logo.png"
